<?php

namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;

class BoardsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

    public function validationDefault(Validator $validator)
    {
        $validator->integer('id');
        $validator->notEmpty('name');
        $validator->notEmpty('title');
        $validator->notEmpty('content');
        return $validator;
    }
}
